### PR TITLE
Remove duplicate menu entry

### PR DESCRIPTION
**Pull request by fixe**

### CODE REVIEW

**Comment by sdepold** [comment]
I wonder if it wouldn't make more sense to delete the api reference entry?

**Comment by janmeier** [comment]
Perhaps it is time to redirect sequelizejs directly to rtd? Have you looked more into a custom theme @sdepold :)?

**Comment by fixe** [comment]
@sdepold as you wish. Let me know if you want me to update this PR.

**Comment by sdepold** [comment]
@janmeier didn't look into it yet. but i think I can spend some time on it during the weekend

**Pull request closed without merging**
